/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///


///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData minus = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_minus = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData plus_circle = IconData(0xf055, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData minus_circle = IconData(0xf056, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
